version: '2'

services:
  app:
    image: 'solution:latest'
    build: .
    restart: always
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/solution
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: 'postgres:14.6-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=solution
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_volume:/var/lib/postgresql/data
volumes:
  db_volume:
