version: '2'

services:
  app:
    image: 'solution:latest'
    build: .
    restart: always
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:postgresql://db:5432/solution",
        "spring.datasource.username" : "user",
        "spring.datasource.password" : "user",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.show-sql" : "true"
      }'
  db:
    image: 'postgres:14.6-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=solution
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_volume:/var/lib/postgresql/data
volumes:
  db_volume:
